services:
  - type: web
    name: nexus-core-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm run start
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html